# Generated by Django 3.2 on 2021-04-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210418_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='shirt_size',
            field=models.CharField(choices=[('A', 'خيارات'), ('B', 'صح وخطأ'), ('C', 'وصل')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='trueAndfalse',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
