# Generated by Django 3.2 on 2021-04-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210420_0651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='shirt_size',
        ),
        migrations.AddField(
            model_name='questions',
            name='question_type',
            field=models.CharField(blank=True, choices=[('A', 'خيارات'), ('B', 'صح وخطأ'), ('C', 'وصل')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
