# Generated by Django 3.2 on 2021-04-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210420_0701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='question_type',
        ),
        migrations.AlterField(
            model_name='questions',
            name='trueAndfalse',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
