# Generated by Django 3.2 on 2021-04-20 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210420_0705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='trueAndfalse',
        ),
    ]
