# Generated by Django 3.2 on 2021-04-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_questions_trueandfalse'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='question_type',
            field=models.CharField(choices=[('A', 'خيارات'), ('B', 'صح وخطأ'), ('C', 'وصل')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='trueAndfalse',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
