# Generated by Django 3.2 on 2021-04-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210420_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question_type',
            field=models.CharField(choices=[('A', 'خيارات'), ('B', 'صح وخطأ'), ('C', 'وصل')], default='A', max_length=2),
        ),
    ]
