# Generated by Django 3.2 on 2021-04-22 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210422_0333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='created_by',
        ),
    ]
